/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-16 13:14:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.news;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.ibatis.reflection.SystemMetaObject;
import news.domain.News;
import news.repository.NewsDAO;
import java.util.ArrayList;
import java.util.List;
import news.util.PagingManager;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 PagingManager pm = new PagingManager(); 
 NewsDAO dao = new NewsDAO(); 
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/inc/header_link.jsp", Long.valueOf(1673868347091L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.ibatis.reflection.SystemMetaObject");
    _jspx_imports_classes.add("news.domain.News");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("news.util.PagingManager");
    _jspx_imports_classes.add("news.repository.NewsDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

List<News> list = dao.selectAll();
pm.init(list, request);
int curPos = pm.getCurPos();
int num = pm.getNum();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>탱고뉴스!</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	function search() {\r\n");
      out.write("		let json = {\r\n");
      out.write("			\"category\" : $(\"#category\").val(),\r\n");
      out.write("			\"keyword\" : $(\"#keyword\").val()\r\n");
      out.write("		}\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"post\",\r\n");
      out.write("			url : \"search_list.jsp\",\r\n");
      out.write("			data : json,\r\n");
      out.write("			success : function(result, status, xhr) {\r\n");
      out.write("				searchList = JSON.parse(result);\r\n");
      out.write("				console.log(searchList);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$(\"#writeNews\").click(function() {\r\n");
      out.write("			location.href=\"/news/write.jsp\";\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#bt_search\").click(function() {\r\n");
      out.write("			search();\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container mt-3\">\r\n");
      out.write("		<h2>뉴스!</h2>\r\n");
      out.write("		<table class=\"table mt-3 border\">\r\n");
      out.write("			<thead class=\"thead-dark\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>No</th>\r\n");
      out.write("					<th>제목</th>\r\n");
      out.write("					<th>작성자</th>\r\n");
      out.write("					<th>등록일</th>\r\n");
      out.write("					<th>조회수</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody>\r\n");
      out.write("				");

				for (int i = 1; i <= pm.getPageSize(); i++) {
					if(num<1) break;
					News news = list.get(curPos++);
				
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>");
      out.print(num--);
      out.write("</td>\r\n");
      out.write("					<td><a href=\"/news/content.jsp?news_idx=");
      out.print(news.getNews_idx());
      out.write('"');
      out.write('>');
      out.print(news.getTitle());
      out.write("</a>\r\n");
      out.write("					");
if(news.getCommentsList().size()!=0){ 
					
      out.write("\r\n");
      out.write("					[");
      out.print(news.getCommentsList().size());
      out.write("]\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>");
      out.print(news.getWriter());
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(news.getContent());
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(news.getHit());
      out.write("</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"5\">\r\n");
      out.write("						<ul class=\"pagination justify-content-center\">\r\n");
      out.write("							");
if(pm.getFirstPage()-1 > 0){ 
      out.write("\r\n");
      out.write("							<li class=\"page-item\"><a class=\"page-link\" href=\"?currentPage=");
      out.print(pm.getFirstPage()-1);
      out.write("\">Prev</a></li>\r\n");
      out.write("							");
}
      out.write("\r\n");
      out.write("							");
for(int i=pm.getFirstPage(); i<=pm.getLastPage(); i++){
									if(i>pm.getTotalPage()) break;
								
      out.write("\r\n");
      out.write("							<li class=\"page-item\"><a class=\"page-link\" href=\"?currentPage=");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a></li>\r\n");
      out.write("							");
}
								if(pm.getLastPage()+1 < pm.getTotalPage()){
							
      out.write("\r\n");
      out.write("							<li class=\"page-item\"><a class=\"page-link\" href=\"?currentPage=");
      out.print(pm.getLastPage()+1);
      out.write("\">Next</a></li>\r\n");
      out.write("							");
} 
      out.write("\r\n");
      out.write("						</ul>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"5\">\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-warning\" id=\"writeNews\">글쓰기</button>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("		<div class=\"row\" style=\"float: right\">\r\n");
      out.write("			<div class=\"input-group mb-3\">\r\n");
      out.write("				<select class=\"input-group-text\" id=\"category\">\r\n");
      out.write("					<option value=\"title\">제목</option>\r\n");
      out.write("					<option value=\"writer\">작성자</option>\r\n");
      out.write("				</select>\r\n");
      out.write("				<input type=\"text\" style=\"width:300px\" class=\"form-control\" id=\"keyword\">\r\n");
      out.write("				<button class=\"btn btn-warning\" id=\"bt_search\">검색</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
